ALTER TABLE `iafas`.`iafas_usuarios` 
ADD COLUMN `CUSUARIO_FIRMA` BLOB NULL AFTER `NUSUARIO_AUTORIZACION`;

ALTER TABLE `iafas`.`iafas_usuarios` 
ADD COLUMN `CUSUARIO_HUELLA_DIGITAL` BLOB NULL AFTER `CUSUARIO_FIRMA`;