DROP TABLE IF EXISTS `IAFAS_ENTIDADES`;

CREATE TABLE `IAFAS_ENTIDADES` (
  `CCODIGO_ENTIDAD` char(3) NOT NULL,
  `VENTIDAD_DESCRIPCION` char(50) DEFAULT NULL,
  `VENTIDAD_ABREVIATURA` char(30) DEFAULT NULL,
  `CESTADO_CODIGO` char(2) DEFAULT NULL,
  `DUSUARIO_CREADOR` datetime DEFAULT NULL,
  `DUSUARIO_FECHA` datetime DEFAULT NULL,
  `VUSUARIO_CREADOR` varchar(20) DEFAULT NULL,
  `VUSUARIO_CODIGO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CCODIGO_ENTIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO IAFAS_ENTIDADES (CCODIGO_ENTIDAD, VENTIDAD_DESCRIPCION, VENTIDAD_ABREVIATURA, CESTADO_CODIGO)
VALUES('001','BANCO DE LA NACIÓN','BN','AC');

INSERT INTO IAFAS_ENTIDADES (CCODIGO_ENTIDAD, VENTIDAD_DESCRIPCION, VENTIDAD_ABREVIATURA, CESTADO_CODIGO)
VALUES('002','BANCO DE CREDITO DEL PERÚ','BCP','AC');

###################################################################################################################

DROP TABLE IF EXISTS `IAFAS_TIPO_CUENTAS`;

CREATE TABLE `IAFAS_TIPO_CUENTAS` (
  `CCODIGO_TIPO_CUENTA` char(3) NOT NULL,
  `VTIPO_CUENTA_DESCRIPCION` char(50) DEFAULT NULL,
  `VTIPO_CUENTA_ABREVIATURA` char(30) DEFAULT NULL, 
  `CESTADO_CODIGO` char(2) DEFAULT NULL,
  `DUSUARIO_CREADOR` datetime DEFAULT NULL,
  `DUSUARIO_FECHA` datetime DEFAULT NULL,
  `VUSUARIO_CREADOR` varchar(20) DEFAULT NULL,
  `VUSUARIO_CODIGO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CCODIGO_TIPO_CUENTA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO IAFAS_TIPO_CUENTAS(CCODIGO_TIPO_CUENTA, VTIPO_CUENTA_DESCRIPCION, VTIPO_CUENTA_ABREVIATURA, CESTADO_CODIGO)
VALUES('003', 'CUENTA TRANSFERENCIAS','CC','AC');

COMMIT;

###################################################################################################################
DROP TABLE IF EXISTS `IAFAS_ENTIDADES_CUENTAS`;

CREATE TABLE `IAFAS_ENTIDADES_CUENTAS` (
  `CCODIGO_ENTIDAD` char(3) NOT NULL,
  `CENTIDAD_CUENTA` char(30) NOT NULL,
  `CCODIGO_TIPO_CUENTA` char(3) DEFAULT NULL,  
  `CESTADO_CODIGO` char(2) DEFAULT NULL,
  `DUSUARIO_CREADOR` datetime DEFAULT NULL,
  `DUSUARIO_FECHA` datetime DEFAULT NULL,
  `VUSUARIO_CREADOR` varchar(20) DEFAULT NULL,
  `VUSUARIO_CODIGO` varchar(20) DEFAULT NULL,
  `NMONTO_CUENTA_TECHO`int(11)  DEFAULT 0,
  `NMONTO_CUENTA_AVANCE`int(11)  DEFAULT 0,
  `NMONTO_CUENTA_SALDO`int(11)  DEFAULT 0,
  PRIMARY KEY (`CCODIGO_ENTIDAD`, `CENTIDAD_CUENTA`),
  CONSTRAINT `IAFAS_ENTIDADES_CUENTAS_FK1` FOREIGN KEY (`CCODIGO_TIPO_CUENTA`) REFERENCES `IAFAS_TIPO_CUENTAS` (`CCODIGO_TIPO_CUENTA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO IAFAS_ENTIDADES_CUENTAS (CCODIGO_ENTIDAD, CENTIDAD_CUENTA, CCODIGO_TIPO_CUENTA, CESTADO_CODIGO, NMONTO_CUENTA_TECHO, 
NMONTO_CUENTA_AVANCE, NMONTO_CUENTA_SALDO)
VALUES('001','123456789','001','AC',1000, 0, 1000);

