CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_IDU_PROGRAMACION_MULTIANUAL_DETALLE`(
xCPERIODO_CODIGO                             	CHAR(4),
xNFUENTE_FINANCIAMIENTO_CODIGO                	INTEGER,
xNTAREA_PRESUPUESTAL_CODIGO                 	INTEGER,
xNCLASIFICADOR_PRESUPUESTAL_CODIGO				INTEGER,
xNPROGRAMACION_MULTIANUAL_GASTO_IMPORTE_A      	INTEGER,
xNPROGRAMACION_MULTIANUAL_GASTO_IMPORTE_B      	INTEGER,
xNPROGRAMACION_MULTIANUAL_GASTO_IMPORTE_C      	INTEGER,
xVUSUARIO_CODIGO                             	VARCHAR(20),
xTIPO 											CHAR,
OUT CODIGO_RESPUESTA	CHAR(1),
OUT MENSAJE_RESPUESTA	VARCHAR(100))
BEGIN
	/*DECLARAMOS VARIABLES*/
    DECLARE nRegistro									INTEGER;
    DECLARE cPeriodo									CHAR(4);
    DECLARE cEstado                     				CHAR(2);
	DECLARE	dMENS_ERROR                     			VARCHAR(1024);
	    
    /*OBTENEMOS EL AF SIGUIENTE*/
    SELECT DATE_FORMAT(SYSDATE()+1,'%Y') INTO cPeriodo;    
    /*VERIFICAMOS QUE EL PERIODO DE LA SOLICITUD DE CREDITO PRESUPUESTAL CORRESPONDA AL AF.*/
    IF cPeriodo!=xCPERIODO_CODIGO THEN
		SIGNAL SQLSTATE  '45000'
		SET MESSAGE_TEXT= 'PERIODO CERRADO. NO PUEDE GENERAR UN CERTIFICADO DE CREDITO PRESUPUESTAL QUE NO SEA DEL PERIODO ACTUAL. VERIFICAR!!.',
		MYSQL_ERRNO = 1643;
    END IF;
    
    /*Buscamos el Registro para INSERTAR, MODIFICAR , ELIMINAR */
    SELECT DISTINCT CESTADO_CODIGO INTO cEstado 
    FROM IAFAS_PROGRAMACION_MULTIANUAL_GASTO WHERE 
    CPERIODO_CODIGO=xCPERIODO_CODIGO AND
    NFUENTE_FINANCIAMIENTO_CODIGO=xNFUENTE_FINANCIAMIENTO_CODIGO AND
    NTAREA_PRESUPUESTAL_CODIGO=xNTAREA_PRESUPUESTAL_CODIGO;

    IF cEstado='CE' THEN
		SIGNAL SQLSTATE  '45000'
		SET MESSAGE_TEXT= 'EL REGISTRO SE ENCUENTRA CERRADO, NO PUEDE REALIZAR NINGUN CAMBIO. VERIFICAR!!.',
		MYSQL_ERRNO = 1643;
    END IF;  

    IF xTIPO = 'I' THEN 
        SELECT IFNULL(COUNT(*),0) INTO nRegistro 
        FROM IAFAS_PROGRAMACION_MULTIANUAL_GASTO_DETALLE WHERE 
        CPERIODO_CODIGO=xCPERIODO_CODIGO AND
		NFUENTE_FINANCIAMIENTO_CODIGO=xNFUENTE_FINANCIAMIENTO_CODIGO AND
		NTAREA_PRESUPUESTAL_CODIGO=xNTAREA_PRESUPUESTAL_CODIGO AND 
        NCLASIFICADOR_PRESUPUESTAL_CODIGO=xNCLASIFICADOR_PRESUPUESTAL_CODIGO;
        
        IF nRegistro=0 THEN
            INSERT INTO IAFAS_PROGRAMACION_MULTIANUAL_GASTO_DETALLE(CPERIODO_CODIGO, CANIO_REGISTRO, NFUENTE_FINANCIAMIENTO_CODIGO, NTAREA_PRESUPUESTAL_CODIGO, 
            NCLASIFICADOR_PRESUPUESTAL_CODIGO, NPROGRAMACION_MULTIANUAL_GASTO_IMPORTE, VUSUARIO_CREADOR, DUSUARIO_CREADOR, VUSUARIO_CODIGO, DUSUARIO_FECHA)     
            VALUES(xCPERIODO_CODIGO, xCPERIODO_CODIGO, xNFUENTE_FINANCIAMIENTO_CODIGO, xNTAREA_PRESUPUESTAL_CODIGO, 
            xNCLASIFICADOR_PRESUPUESTAL_CODIGO, xNPROGRAMACION_MULTIANUAL_GASTO_IMPORTE_A, xVUSUARIO_CODIGO, SYSDATE(), xVUSUARIO_CODIGO, SYSDATE());

            INSERT INTO IAFAS_PROGRAMACION_MULTIANUAL_GASTO_DETALLE(CPERIODO_CODIGO, CANIO_REGISTRO, NFUENTE_FINANCIAMIENTO_CODIGO, NTAREA_PRESUPUESTAL_CODIGO, 
            NCLASIFICADOR_PRESUPUESTAL_CODIGO, NPROGRAMACION_MULTIANUAL_GASTO_IMPORTE, VUSUARIO_CREADOR, DUSUARIO_CREADOR, VUSUARIO_CODIGO, DUSUARIO_FECHA)
            VALUES(xCPERIODO_CODIGO, xCPERIODO_CODIGO+1, xNFUENTE_FINANCIAMIENTO_CODIGO, xNTAREA_PRESUPUESTAL_CODIGO,  
            xNCLASIFICADOR_PRESUPUESTAL_CODIGO, xNPROGRAMACION_MULTIANUAL_GASTO_IMPORTE_B, xVUSUARIO_CODIGO, SYSDATE(), xVUSUARIO_CODIGO, SYSDATE());

            INSERT INTO IAFAS_PROGRAMACION_MULTIANUAL_GASTO_DETALLE(CPERIODO_CODIGO, CANIO_REGISTRO, NFUENTE_FINANCIAMIENTO_CODIGO, NTAREA_PRESUPUESTAL_CODIGO, 
            NCLASIFICADOR_PRESUPUESTAL_CODIGO, NPROGRAMACION_MULTIANUAL_GASTO_IMPORTE, VUSUARIO_CREADOR, DUSUARIO_CREADOR, VUSUARIO_CODIGO, DUSUARIO_FECHA)
            VALUES(xCPERIODO_CODIGO, xCPERIODO_CODIGO+2, xNFUENTE_FINANCIAMIENTO_CODIGO, xNTAREA_PRESUPUESTAL_CODIGO, 
            xNCLASIFICADOR_PRESUPUESTAL_CODIGO, xNPROGRAMACION_MULTIANUAL_GASTO_IMPORTE_C, xVUSUARIO_CODIGO, SYSDATE(), xVUSUARIO_CODIGO, SYSDATE());
			
            SET CODIGO_RESPUESTA  = '0';
			SET MENSAJE_RESPUESTA = 'GRABACION EXITOSA!';
            
        END IF;
    ELSE
        IF xTIPO = 'D' THEN
            /*ELIMINA REGISTROS DE LA DETALLE*/
            DELETE FROM IAFAS_PROGRAMACION_MULTIANUAL_GASTO_DETALLE WHERE 
            CPERIODO_CODIGO=xCPERIODO_CODIGO AND
			NFUENTE_FINANCIAMIENTO_CODIGO=xNFUENTE_FINANCIAMIENTO_CODIGO AND
			NTAREA_PRESUPUESTAL_CODIGO=xNTAREA_PRESUPUESTAL_CODIGO AND 
			NCLASIFICADOR_PRESUPUESTAL_CODIGO=xNCLASIFICADOR_PRESUPUESTAL_CODIGO;
        ELSE
           # SIGNAL SQLSTATE  '45000'
			#SET MESSAGE_TEXT= 'NO EXISTE EL REGISTRO PARA MODIFICAR/ELIMINAR. VERIFICAR!!.',
			#MYSQL_ERRNO = 1643; 
              SET CODIGO_RESPUESTA  = '0';
			SET MENSAJE_RESPUESTA = 'ELIMINACIÓN EXITOSA!';
        END IF;
    END IF; 
    COMMIT;
END